apiVersion: v1
kind: Service
metadata:
  name: mcp-sample
spec:
  ports:
  - name: grpc
    port: 15010
    targetPort: grpc
  selector:
    app.kubernetes.io/name: mcp-sample

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-sample
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp-sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp-sample
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: server
        image: docker.io/tanjunchen/mcp-ovs-xds-server:v1
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: grpc
          containerPort: 15010
