apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: tanjunchen
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', 'echo Container 1 is Running ; sleep 3600']
