FROM golang:1.18.2-alpine3.16 AS build-env
ADD . /src
ENV GOPROXY https://goproxy.cn
RUN cd /src && CGO_ENABLED=0  GOARCH=amd64 go build -o goapp

FROM golang:1.18.2-alpine3.16

ARG service_version
ENV SERVICE_VERSION ${service_version:-header}

WORKDIR /app
COPY --from=build-env /src/goapp /app/

ENTRYPOINT ["./goapp"]
