FROM golang:1.18.2-alpine3.16 AS build-env
ADD . /src
ENV GOPROXY https://goproxy.cn
RUN cd /src && GOARCH=amd64 CGO_ENABLED=0 go build -o goapp

FROM ubuntu:xenial

RUN apt-get -y update
RUN apt-get --yes install libav-tools bash  automake autoconf  make

ARG service_version
ENV SERVICE_VERSION ${service_version:-header}

WORKDIR /app
COPY --from=build-env /src/goapp /app/

ENTRYPOINT ["./goapp"]
